name: Translations
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: 'Checkout repo'
          uses: actions/checkout@v2

        - name: Translate
          uses: cartogram/deepl-action@0.0.1
          with:
            auth-key: '${{ secrets.DEEPL_AUTH_KEY }}'
            source-languages: 'en'
            target-languages: 'de,cs'
            language-directory: './dictionaries'

        - name: Commit changes
          uses: devops-infra/action-commit-push@master
          with:
              github_token: '${{ secrets.GITHUB_TOKEN }}'
              commit_prefix: '[Auto] '
              commit_message: 'Adding updated localization files'
              force: false
              target_branch: ${{steps.vars.branch_name.current_branch}}
