name: Translations
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: 'Checkout repo'
          uses: actions/checkout@v2

        - name: Translate
          uses: cartogram/deepl-action@0.0.4
          with:
            auth_key: '${{ secrets.DEEPL_AUTH_KEY }}'
            source_language: 'en'
            target_languages: 'de,cs'
            language_directory: './dictionaries'
        - name: Commit changes
          uses: EndBug/add-and-commit@v9
          with:
            author_name: Bot
            author_email: mseccafien@gmail.com
            message: 'translations'
            add: '**/*.json'
